#---
#kind: Deployment
#apiVersion: apps/v1
#metadata:
#  name: nodejs-app
#  namespace: default
#  labels:
#    app: nodejs-app
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: nodejs-app
#  template:
#    metadata:
#      labels:
#        app: nodejs-app
#    spec:
#      containers:
#      - name: nodejs-app
#        image: nginx
#        ports:
#          - containerPort: 5678
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nodejs-app
#  namespace: default
#spec:
#  selector:
#    app: nodejs-app
#  type: NodePort
#  ports:
#  - name: http-service
#    targetPort: 5678
#    port: 80
#


apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: maryambee/helm-goapp-isw:v1
        ports:
        - containerPort: 5678
