apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  labels:
    app: http-echo-isw
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: http-echo-isw
  template:
    metadata:
      labels:
        app: http-echo-isw
    spec:
     containers:
       - name: {{ .Values.image.name }}
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
         imagePullPolicy: {{ .Values.image.pullPolicy }}
         ports:
           - name: http
             containerPort: {{ .Values.service.containerPort }}

